theme: jekyll-theme-minimal
title: Algorithmic Experiences
description: Link repository for the Algorithmic Experiences Newsletter
author:
  twitter: polgarp
excerpt_separator: <!--more-->
site_baseurl: https://polgarp.github.io/alg-exp
paginate: 42
gems:
  - jekyll-feed
  - jemoji
  - jekyll-titles-from-headings
